### PR TITLE
added pocketsphinx as an always-on recognizer for 'computer,' activated ...

### PR DESCRIPTION
**Pull request by thomasweng15**
...using the '-c' command line argument.

The '-c' command line argument stands for continuous: if 'python listen.py -c' is run, Pi-Voice starts the pocketsphinx subprocess to listen for the word 'computer.' Upon hearing the activation word, Pi-Voice will run the listen() function. If the '-c' argument is omitted, Pi-Voice will just run the listen() function immediately and then exit.

This change requires pocketsphinx. I think the only packages necessary are python-pocketsphinx and python-sphinxbase (which I installed on ubuntu using synaptic package manager), but I have not fully tested if this is true. Here is a full list of packages I have installed relating to pocketsphinx:
- libsphinxbase1
- libpocketsphinx1
- pocketsphinx-utils
- pocketsphinx-lm-wsj
- pocketsphinx-hmm-wsj1
  To test pocketsphinx installation, you can run pocketsphinx_continuous in the terminal. Let me know if you have any questions!

Thomas

### CODE REVIEW

**Comment by rob-mccann** [comment]
Awesome work. I'll give it a test later tonight.

Out of curiosity: could we improve accuracy by reducing the vocabulary?

**Comment by rob-mccann** [comment]
This looks super awesome too https://github.com/ndbroadbent/raspberry_picrowave/tree/master/voice_control

**Comment by thomasweng15** [comment]
I read about the pi microwave project; I'll check it out! Regarding the vocabulary, I wanted to reduce false positives, but the corpus isn't as refined as it could be. I wonder if adding grammar models will help accuracy as well. There are several aspects of continuous pocket sphinx listening that I'd like to refine over time, and perhaps the raspberry picrowave project will have suggestions as well.

**Comment by thomasweng15** [comment]
Have you been able to test it or get pocketsphinx running? Is there anything you would like me to change, besides possibly slimming down the corpus?

**Comment by rob-mccann** [comment]
Hi Thomas, 

I'll have time next week :)

**Pull request closed without merging**
