### PR TITLE
added Julius as an always-on listener for 'computer'.

### PR DESCRIPTION
**Pull request by thomasweng15**
I added Julius speech recognition by altering listen.py and adding a folder called Julius containing the  grammar and vocab information. There are extra vocab words and grammar constructs than necessary to just listen for 'computer', but I have found that Julius without this extra information Julius tends to hear many false positives. Currently the extra vocab words and grammar were not added with any particular idea in mind, but in future work we can organize them more systematically.

I put all the code necessary for Julius to work in listen.py, because I was not sure how you wanted it organized. There is most likely a more efficient way of organizing the code that can be worked out. The code as it is works fine, but style and 'object-orientedness' could be improved on.

And as a last but obvious note, julius and julius-voxforge will need to be installed for the program to work. Let me know if you have any questions or comments!

### CODE REVIEW

**Comment by rob-mccann** [comment]
It looks like there's some conflicts here.

You'll need to do the following:

`git remote add upstream git://github.com/rob-mccann/Pi-Voice.git`
`git pull --rebase upstream concept`
`git push origin concept`

Drop me an email if you have any trouble :)

**Comment by thomasweng15** [comment]
I am not sure if I rebased correctly. Are the conflicts resolved or are further steps necessary?

**Comment by rob-mccann** [comment]
Nope the conflicts aren't resolved :(

Had a quick look, this might help.
http://stackoverflow.com/questions/13561004/merging-upstream-git-changes-with-pending-pull-requests

**Comment by rob-mccann** [comment]
You'll need to make sure this is one commit, you may need to re-fork or create a new branch from before your commits and re-implement your code.

**Comment by thomasweng15** [comment]
working on it

**Comment by rob-mccann** [comment]
I'm part-way through importing it - I was having some trouble getting Julius to hear be on osx, I'll try it on ubuntu a bit later.

**Comment by thomasweng15** [comment]
have you tried using pocketsphinx on your mac?

**Comment by rob-mccann** [comment]
I got started with pocketsphinx, I've not yet got it working :/

**Comment by thomasweng15** [comment]
I posted a new pull request using pocketsphinx, with simpler code organization. We can add julius as an option in the future if it is desirable!

**Pull request closed without merging**
